### ISSUE TITLE
eris chains make --known not working

### ISSUE THREAD

**Issue by joluHo** [eris-ltd/eris-cli#1039]
- [ ] `docker version` - 1.12.1
- [ ] `eris version` - 0.12.0-rc3
- [ ] `go version` - go1.6.3
- [ ] `docker-machine version` - 0.7.0
- [ ] operating system details  - linux/amd64
- [ ] Expected the chain to be created or an informative error to be shown
- [ ] Apparently nothing happens - neither the chain nor the files are created
- [ ] steps to reproduction - Create folder with chain name, move accounts.csv and validators.csv to the folder and run `(~/.eris/chains/marketP2) $ eris chains make marketP2 --known --validators validators.csv --accounts accounts.csv -d`

After the command execution there is only the .csv files on the folder:

```
(~/.eris/chains/marketP2) $ ls -l
total 8
-rw-r--r-- 1 jose jose 2930 Oct 14 11:28 accounts.csv
-rw-r--r-- 1 jose jose  530 Oct 14 11:28 validators.csv
```

The only error shown is the following:

```
Directory missing                 destination=/home/eris/.eris/chains/marketP2
                                        error=Container interactive-e3a81218-2f38-40a6-b30a-c37349f09085 exited with status 1
Running data container                        marketP2-41b07a9e-620f-4f5e-86f4-9ab3bec1c39e
```

But I have that same error when deploying contracts in other chain even if the contract is well deployed.

Complete command output:
https://gist.github.com/joluHo/17e8f1b11d30a3ce3f8db07c6b1b6c06

**Comment by pietv** [comment]
@joluHo thank you for reporting the issue. I have managed to reproduce it and currently in the process of making a fix. I'll get back to you with a fix or a workaround.

**Comment by pietv** [comment]
@joluHo please try to use this binary: https://dl.dropboxusercontent.com/u/370040684/eris (CLI #develop branch with a tentative fix), to repeat your scenario of making a chain with the `--known` flag.

Also, please, remove all old chains and reinitialize the `~/.eris` directory (the #develop version will need to pull #develop images) before starting your experiment:
```bash
$ rm -fr ~/.eris
$ eris clean -y
$ eris init -y
```
Thank you!

**Comment by joluHo** [comment]
@pietv I just tried again with the develop binary your provided. Even if I followed the steps you sugested the problem persists. No files created and no error shown.
Just let me know if I can provide you with more info.

Thanks

**Comment by pietv** [comment]
@joluHo thank you for the feedback! sorry the fix didn't work for you: it was really a shot in the dark because i haven't managed to reproduce your issue (I fixed a panic and an data importing problem, but apparently there was something else amiss).

Right now, following your recipe again, I experience the same issue (no other files are created in the chains folder after `chains make`), so I have something to work with. I'd like to ask you to run the `eris chains make` command with the `-d` flag to be able to compare outputs.

And another question: have you copied the `accounts.csv` and `validators.csv` files from another chain as is or edited/modified some data in them manually also? 

Thank you!

**Comment by joluHo** [comment]
@pietv here you have the command output:
https://gist.github.com/joluHo/ea872e331f754ecab4051a059ebaf08e 

I just copied the files from another chain without modifications.

**Comment by pietv** [comment]
@joluHo thanks vm! I will update you shortly.

**Comment by pietv** [comment]
@joluHo i've implemented the fix for the `make --known` command in the #fix-chains-known branch. Please try your experiment when you are able to, thanks! For your convenience, here's also a binary with the fix: https://dl.dropboxusercontent.com/u/370040684/eris_0.12.0-develop_linux_amd64
Please note that the `eris chains make --known` command is to generate a new `genesis.json` file only, not to create a new chain. Thanks!

**Comment by pietv** [comment]
The issue has been merged to #master. Please reopen if you experience it again.
