### ISSUE TITLE
[Core] Sign packages with a better algorythm than SHA1

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#1120]
**Problem** -- current versions of debian reject apt-get packages signed with a SHA1 based DSA. In general SHA1 is breakable and should not be used.

**Solution** -- currently available packages should utilize SHA256 DSAs which are future proofed and accepted by operating systems.

**Comment by AFDudley** [comment]
I'm pretty sure this requires the creation of a new key:
https://keyring.debian.org/creating-key.html
https://riseup.net/en/security/message-security/openpgp/best-practices#stated-digest-algorithm-preferences-must-include-at-least-one-member-of-the-sha-2-family-at-a-higher-priority-than-both-md5-and-sha1
https://lists.debian.org/debian-devel-announce/2010/09/msg00003.html

OR changing the config before:
https://lists.debian.org/debian-devel-announce/2010/09/msg00003.html

So that it doesn't insert the SHA1 version.

**Comment by pietv** [comment]
@compleatang which piece of software did you or a customer use on Debian to install the package to see the error about SHA1. Tried `apt-get` for `wily`, `jessie`, `stretch` — all work with the current setup. Will investigate further.

**Comment by pietv** [comment]
Hash algorithm of the current signing key is `SHA256`:
```
$ pgpdump *.asc
Old: Signature Packet(tag 2)(319 bytes)
        ...
        Hash alg - SHA256(hash 8)
```

**Comment by compleatang** [comment]
Think it was apt-get for `stretch` but even on Ubuntu 16.04 LTS I get the following:

```

**Comment by pietv** [comment]
`xenial` works fine as well (with cleaned up keys and apt caches). Thanks for the error message, should be useful: will try the 16.04 LTS .iso image with VirtualBox this time.

**Comment by compleatang** [comment]
Hmmm. I cleaned my keys and apt cache via this -> http://www.commandlinefu.com/commands/view/14024/clean-apt-get-and-gpg-cache-and-keys but the error still persists on xenial.

**Comment by pietv** [comment]
Caught it on a freshly installed xenial: signature fixed.

If you will be testing, please make sure the MD5 sum of the APT-GPG-KEY file is `47187f275e3810a0c50fd363adb6fefd` — CloudFront is catching up slowly: 
```
$ curl https://apt.monax.io/APT-GPG-KEY|md5sum
...
47187f275e3810a0c50fd363adb6fefd
```

**Comment by compleatang** [comment]
Fixed for me now! Thanks @pietv
