### ISSUE TITLE
Error initiating default services

### ISSUE THREAD

**Issue by arunkumarsekar** [eris-ltd/eris-cli#1129]
some one please help me to overcome this issue ..
I am using Ubuntu 14.04 LTS

![eris](https://cloud.githubusercontent.com/assets/2208785/20960598/3b3307cc-bc87-11e6-9fc3-a07124dfe7e8.jpg)
![eris-2](https://cloud.githubusercontent.com/assets/2208785/20960599/3b341036-bc87-11e6-8f58-030113f87039.jpg)

**Comment by zramsay** [comment]
hi @arunkumarsekar are you behind a firewall? 

You can try `git clone https://github.com/eris-ltd/eris-services.git $HOME/.eris/services` to get the service definition files.

**Comment by sathishmanoharan** [comment]
Hi Zach, I had the same issue with Ubuntu 14.04 and resolved it as you mentioned. But it is failing in 'eris chains make test_chain' due to the missing proxy details. I have updated /etc/default/docker. Can you let me know where else proxy details have to be added?

![eris_proxy_error](https://cloud.githubusercontent.com/assets/18713130/21051186/083ed2d2-be45-11e6-9834-f76d75eacc13.png)

**Comment by zramsay** [comment]
@sathishmanoharan did `eris init` not pull the docker images? Could you try pulling manually? (e.g., with `docker pull`? This might be a new proxy issue with docker and we'll investigate. Also, which `eris version` are you on?

**Comment by sathishmanoharan** [comment]
@zramsay Thanks for your reply. I am running docker as non-root user but added user to the docker group. I am able to pull the images using sudo. But facing issues in starting the chain. Not sure if chain has created properly. But I can see test_chain directory has been created with the required files.

![image](https://cloud.githubusercontent.com/assets/18713130/21182176/bd2cc8b2-c227-11e6-9f82-fd4ba4818838.png)
![image](https://cloud.githubusercontent.com/assets/18713130/21182192/cfa3af92-c227-11e6-8d9d-51da0f44267f.png)
![image](https://cloud.githubusercontent.com/assets/18713130/21182213/e95fde6a-c227-11e6-8ce2-b543dd65fd8c.png)
![image](https://cloud.githubusercontent.com/assets/18713130/21182243/06f68ab4-c228-11e6-8e9a-65a9211ffa58.png)
![image](https://cloud.githubusercontent.com/assets/18713130/21182421/0ab2d9b8-c229-11e6-938c-0abf94bc08c2.png)

This is the docker and docker-machine details. Any issue you can notice?
![image](https://cloud.githubusercontent.com/assets/18713130/21182396/ed3e0fba-c228-11e6-8bee-b2a9756d02b2.png)

**Comment by zramsay** [comment]
@sathishmanoharan I notice two things: 1) after running `eris chains make`, the `eris chains start` command requires `--init-dir ~/.eris/chains/test_chain`, 2) since you're on linux, docker-machine is not required but if you are wanting to use it, it'll need to be put "in-scope". This can be done with `eval $(docker-machine env eris)`. The `ACTIVE` field should then go from `-` to `*` when running `docker-machine ls`

**Comment by sathishmanoharan** [comment]
Hi @zramsay , I made the eris machine to be 'in-scope' by running eval command. (Previously, i used sudo with 'docker-machine' commands and that caused the problems with env variables)
![image](https://cloud.githubusercontent.com/assets/18713130/21263706/41afeb36-c3be-11e6-99f0-17ea41e7a7ce.png)
Also ran  'eris chains start' with init-dir flag. Yet chain is not starting throwing the error. 'eris chains ls' is not listing the chain  after make command. Am i missing something? Or is there an issue with my setup? Kindly help
![image](https://cloud.githubusercontent.com/assets/18713130/21263798/bb13d3fc-c3be-11e6-962e-ddfb80dbefe0.png)
![image](https://cloud.githubusercontent.com/assets/18713130/21263811/d0b45f2e-c3be-11e6-8f56-7a71b99ea260.png)
![image](https://cloud.githubusercontent.com/assets/18713130/21263821/e514f46a-c3be-11e6-851a-ab22e3a3f346.png)
![image](https://cloud.githubusercontent.com/assets/18713130/21263876/4614846a-c3bf-11e6-8723-f73fa1132134.png)

**Comment by arunkumarsekar** [comment]
@zramsay yes, i am behind corporate firewall... "eris init" command ask for proxy authentication is there any place to configure proxy details in eris or please suggest me right approach to install eris behind proxy 
![screenshot from 2016-12-19 20 02 59](https://cloud.githubusercontent.com/assets/2208785/21316401/8b382718-c626-11e6-95e3-f8ad46d7bf35.png)
??

**Comment by zramsay** [comment]
@arunkumarsekar you can pull each docker image individually via `docker pull quay.io/*` where the `*` is each image from within `fmt.Sprintf` in this file: https://github.com/eris-ltd/eris-cli/blob/master/version/images.go ... this worked for @sathishmanoharan

@sathishmanoharan the first thing I would try is restarting your docker-machine then going though https://docs.docker.com/engine/installation/linux/ubuntulinux/#/manage-docker-as-a-non-root-user in order to avoid running with `sudo`.

**Comment by sathishmanoharan** [comment]
@zramsay Found that docker-machine needs proxy configuration. Followed this link http://mflo.io/2015/08/13/docker-machine-behind-proxy/ for docker-machine proxy configuration. Chain has started fine now. Thanks for your guidance.
Would be helpful to others if this information is added to Monax documentation.

**Comment by zramsay** [comment]
thanks @sathishmanoharan 
note: see #1150 since this may affect your workflow
