### ISSUE TITLE
chain registration and fetching

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#121]
Add flag to squelch registration.

**Comment by ebuchman** [comment]
chains new container should be linked to keys
use `--register <address>` to specify the address you want to sign from. This address should be a valid account on the etcb chain.  by default we don't register since it will err unless you give a known address.

registration means posting `$CHAIN_ID:genesis` and `$CHAIN_ID:seeds` to the etcb name-reg, where the data for the former is the genesis file and the latter is the ip/port of the seed. This seed should (probably) be the host that's running `chains new` - the address can be passed in with `--env="NEW_P2P_SEED=<ip>:<port>"`. down the road we can have some protocol for figuring out our public ip (eg. we can ask the etcb nodes to tell us, or just assume we're not behind a nat and use go)

`eris chains install` is the reverse of this, grabbing the genesis and seed of the given chain from the etcb name reg and running it locally. if the chain we're installing is the etcb chain itself, we grab the genesis and seed from rpc endpoints (/genesis and /status)

**Comment by compleatang** [comment]
I was *just* thinking thru how we'd install `etcb` since most everything else will work from its backbone.

**Comment by ebuchman** [comment]
ya there's logic for that. 

I'm thinking now that register should be its own command, rather than hitching it on new. it's gonna need at least 2 flags and could use more - would be better as own command

**Comment by compleatang** [comment]
@ebuchman we're good here no? should we close this in favor of more specific issues as needed?

**Comment by ebuchman** [comment]
yup
