### ISSUE TITLE
eris files cache problem

### ISSUE THREAD

**Issue by tom-seddon** [eris-ltd/eris-cli#137]
(eris-cli commit 01a36033bb4bafb1f6d77999a1e5dc8206791e02, obtained and built as per the instructions)

I've added a file to IPFS with eris files put, visible here: http://gateway.ipfs.io/ipfs/QmX41hWEUGJnQPJxJnwEquLc6mNvfXsZe4GxayJkURtYtY

I can cat it: 

    % eris files cat QmX41hWEUGJnQPJxJnwEquLc6mNvfXsZe4GxayJkURtYtY
    This is a test file for IPFS.

But I can't cache it:

    % eris files cache QmX41hWEUGJnQPJxJnwEquLc6mNvfXsZe4GxayJkURtYtY -v
    IPFS is running.
    IPFS is running.
    PINing file to IPFS. File =>	QmX41hWEUGJnQPJxJnwEquLc6mNvfXsZe4GxayJkURtYtY
    Caching =>			QmX41hWEUGJnQPJxJnwEquLc6mNvfXsZe4GxayJkURtYtY:http://0.0.0.0:5001/api/v0/pin/add?arg=QmX41hWEUGJnQPJxJnwEquLc6mNvfXsZe4GxayJkURtYtY
    error json unmarshaling body invalid character 'p' looking for beginning of value

As discussed on #eris-dev.

Thanks,

--Tom

**Comment by zramsay** [comment]
This isn't actually a bug but rather bad error handling on our part. The response from IPFS wasn't unmarshaling because it was unexpected & reads `pin: [hash] already pinned recursively`. A file added with `eris files put` to IPFS is pinned (i.e., cached) by default (this is the `ipfs add` default functionality that `eris files put` wraps around). In other words, it's only possible to `eris files cache` a file that you don't already have.
