### ISSUE TITLE
`eris init` behavior could be improved significantly

### ISSUE THREAD

**Issue by taoeffect** [eris-ltd/eris-cli#174]
Problems:

- `eris init` takes too long
- It sits there not providing any feedback
- The docs don't say what it will do, nor does the command itself tell you what it's doing at any point
- When it fails, it gives a totally obscure message: #173 

Suggestions:

- The docs should explain what the command will do, and they should also state when the command needs to be run (once? twice? periodically? sometimes? why?)
- The command itself should provide immediate output when it's run, explaining what it does, and continual status updates.
- The error messages should be descriptive and provide hints/instructions on how to fix the problem.

**Comment by compleatang** [comment]
The reason eris init takes time is that it is setting up a virtual machine. That is the big delay you experienced. Am pushing a fix now that will give users and option to install this virtual machine or not. 

We will also increase the logLevel on the creating notification so that it displays even if the command is given without the `-v` or `-d` flags. 

Descriptions response in docs #4.

**Comment by zramsay** [comment]
@taoeffect it's been improved (well, fixed) and is much saner now. Prompts should better explain what's going on too

**Comment by taoeffect** [comment]
@zramsay nice work! :smile: :+1:
