### ISSUE TITLE
`eris chains rm`

### ISSUE THREAD

**Issue by slowtokyo** [eris-ltd/eris-cli#193]
When I create a new chain and then try to remove it with the captioned command it does not seem to actually remove the command. I can see the data container in Kitematic.

The relevant debug code is below.
```
bash-3.2$ eris chains rm chaintoremove -d
Connecting to the Docker Client via TLS.
	URL =>			tcp://192.168.99.100:2376
	Docker Cert Path =>	/Users/MacBookAir/.docker/machine/machines/default
Connected over TLS.Successfully connected to Docker daemon
Setting IPFS Host
Set ERIS_IPFS_HOST to =>	http://192.168.99.100
Does Chain Exist? =>		chaintoremove:1
Could not find container =>	chaintoremove:1
That chain's container does not exist.
bash-3.2$ eris chains known -d
Connecting to the Docker Client via TLS.
	URL =>			tcp://192.168.99.100:2376
	Docker Cert Path =>	/Users/MacBookAir/.docker/machine/machines/default
	chaintoremove
	warwick
Connected over TLS.Successfully connected to Docker daemon
Setting IPFS Host
Set ERIS_IPFS_HOST to =>	http://192.168.99.100
```

**Comment by compleatang** [comment]
(assume we got you past the services challenge :) ). Great question, but answer requires explaining a bit about the chain "boot" process.

Looks like you don't have a container for the chains process. If you only did `eris chains new chaintoremove` (meaning you never did `eris chains start chaintoremove`) then what will happen is that the chain formation (hashing) process within eris:db container will run with the `eris_data_chaintoremove_1` container's volumes mounted in it. And then that container will be removed leaving only the data container. If you do not run `eris chains start chaintoremove` then eris will not make a chain container so that is why is is reporting `Could not find container` after asking if `Does Chain Exist?`.

What the `eris chains rm` without any flags does is remove the `eris_chains_chaintoremove_1` container. Since eris can't find that container (indeed, it won't exist if you never did `eris chains start`) that's why it's not doing anything. 

If you want to remove the data container && the chain container then you'd run `eris chains rm -x chaintoremove` and if you want to remove the chain definition file also you'd add the `-f` (for file flag). Since there is no chain container to remove, if you'd like to just remove the data container then you'd do, `eris data rm chaintoremove`.

At the end (or at any point) you can `docker ps -a` to list all of your containers at the Docker "porcelain" level rather than the eris "plumbing" level.

**Comment by compleatang** [comment]
One more point is that `known` will just list the files in the directory (so `eris chains known` lists the files it can find in `~/.eris/blockchains`, services the same). 

On the other hand `ls` will list the containers that exist for the subset (services, chains, etc.).

Finally, `ps` will list the containers that exist and are running for the subset (services, chains, etc.). 

So those three listing functions operate slightly differently depending on what you're trying to achieve.

**Comment by slowtokyo** [comment]
Cool. That makes sense. Thanks for the explanation!
