### ISSUE TITLE
fix docker-machine / OSX bootup sequence

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-cli#204]
from #196 
enhancement b/c works fine if `docker-machine` / VMBox is configured properly
bug b/c it'd be nice if we handled it for the user
0.12 b/c this'll take me awhile

**Comment by compleatang** [comment]
If the $DOCKER_HOST and $DOCKER_CERT_PATH variables are set this will already get taken care of. If eris does not find these set when it is checking the connection to docker then it check the "default" VM if that doesn't work then it will prompt the user if they want to create a dm (by default named eris). 

This is the current functionality, BTW.

**Comment by compleatang** [comment]
Can someone confirm whether this is still an issue on OSX? cc @taoeffect

**Comment by zramsay** [comment]
I think we just (still) need better documentation on launching docker - i.e., making all the nuances super explicit. Seems the biggest issue for users is oversight of the commands docker's stdout tells one to run (rather than, say, prompting for it)

**Comment by compleatang** [comment]
<rant>

Right. We have lots of documentation needs right now and lots of folks are able to get over this hurdle to the deeper stuff which we currently have *no* docs for. 

Have been answering tickets a lot recently about this and we need to be spending our time getting beyond the *holy fuck its docker*. Yes its docker, get on with it. Because plenty of other developers have too. :)

Eventually I'm happy to circle back around and clean up these nuances and be super explicit for users as to all of the edge and corner cases, but right now we need to document the middle of the road cases deeper in the funnel before we start worry about the edge cases for newbs. 

If there's some quick wins here I'm all for those, but I'm not for us continuing to getting this OSX onboarding grandmother friendly (just now; eventually yes, but we have bigger priorities right now).

</rant>

**Comment by taoeffect** [comment]
@compleatang wrote:
> Can someone confirm whether this is still an issue on OSX? cc @taoeffect

Yes, it seems to be. There should be a `*` under `ACTIVE` but there isn't. Also, noticing some weird things in #253.

```
-> % eris init
The marmots could not find a docker-machine virtual machine they could connect to.
Our marmots recommend that you have a vm dedicated to eris dev-ing.
Would you like the marmots to create a machine for you? (y/n): y
The marmots will create an eris machine.
Creating the eris docker-machine.
This will take some time, please feel free to go feed your marmot.
-> % docker-machine ls
NAME   ACTIVE   DRIVER       STATE     URL                         SWARM
eris            virtualbox   Running   tcp://192.168.99.100:2376
```

**Comment by compleatang** [comment]
closing this as it was related to #253 which is fixed now.
