### ISSUE TITLE
Better container+data lifecyle management

### ISSUE THREAD

**Issue by taoeffect** [eris-ltd/eris-cli#207]
I'm not sure if there are even docs available on this, but this is confusing (from `eris help`):

```
  data        Manage Data Containers for your Application.
  files       Manage Files containers for your Application.
```

... "files" are not "data"?

That's kinda an issue in itself (and feel free to break this issue up into multiple ones or tell me to do it).

This is part of a larger problem. Let me try to setup the context for you:

- `eris`'s intimate integration with Docker is a huge obstacle to adoption for `eris`, as it requires learning `eris` along with Docker, which is huge and *weird* (not to mention the million other things `eris` wraps around or integrates with).
- Running most `eris` commands initially results in *massive* amounts of data being downloaded (without telling the user that this is about to happen! See #205).
- Newcomers _have no idea_ where this data is being downloaded to or why.
- In briefly using `eris`, just running `chains new` and `ipfs` results in ~900MB in `~/.docker`. It's not OK to just litter people's disks like this without warning them or giving them the tools they need to manage it. (Speaking of which, does `eris` make sure there's enough space available before downloading? If not, that should be opened up as another issue.)
- It appears that "developing with `eris`" means "be prepared to quickly use up a whole bunch of hard disk space and for frequent half gig surprise downloads". Imagine if a developer is on the road and using their cell phone's WiFi for internet. They wouldn't be able to work and might even get charged a whole bunch of $$ for overages on their plan.

So, there needs to be the following:

- Clear communication in all long running commands about what's happening (how big of a file is being downloaded and why and to where), perhaps some progress meter, etc. See #205.
- The concept of "containers" is crazy vague and confusing. Perhaps some new abstraction should be invented to help people wrap their heads around what's going on, or they need to be explained better.
- There shouldn't be two similarly named commands like `eris files` and `eris data`
- There should be clear instructions provided by `eris` as to how to manage the lifecycle of *both* the downloaded data/containers (are these two different things?) and the running containers/services.
- There should be a command like `eris status` that shows clearly:

    1. How many containers there are.
    2. Where they are.
    3. What they represent and what their status is.
    4. How big they are.
    5. What services are running by which containers and clearly showing the relationship between containers/services/files/data

In a word: UI/UX.

Because so far, `eris` has managed to overwhelm and confuse a veteran developer, and if it can do that to me, then what will it do to 99% of the devs who encounter it?

Also: the more confusing `eris` (the cli) is, the harder it makes my job of documenting everything, and that also means that your docs will end up being longer and less approachable than they otherwise could be.

**Comment by ebuchman** [comment]
Greg, these are great points and thanks for spelling them out.

Indeed, tight docker integration is an obstacle. But the very purpose of this tool is to make using docker to orchestrate decentralized systems running multiple services as simple as possible. Indeed, there are a number of issues, revolving mostly around the need for large images and understanding containers and their composition.

Let me first point out that all the tools eris-cli wraps are available without docker, if you want to do the plumbing. That basically means installing tendermint or erisdb, the eris-keys daemon, the mint-client tools, and ipfs, and making sure the configurations are all set. This is always possible and will always be supported, and you can see an example tutorial here: https://github.com/eris-ltd/mint-client/wiki/Tutorial:-Mintgen-&-Erisdb. For example this is how Tyler is doing his development, and how I do it before it's ready for integration into a docker image.

Allow me to motivate the use of docker with an example: https://github.com/eris-ltd/mindy
mindy itself is a simple program that reads names off the tendermint blockchain and writes them to a file that a tinydns server can read from. hence we can serve blockchain's name reg over dns. Installing and setting up tinydns can be overwhelming. Shutting it down is supposed to be impossible. Getting the pieces up and running on different platforms is not straight forward - example due to licensing issues a special patch required for a debian version. And this is just for tinydns. What if I want to run a dozen other services that talk to my blockchain? Using docker eliminates all this complexity, allowing everything to be booted in a cross platform manner with eg. `eris services start mindy`

Yes this means we're locked into docker, but the entire industry is betting on docker right now, and if we have to sacrifice some user groks in the short term we believe it will pay off by having aligned with docker early on.

On the other hand, I agree completely that we need to be more transparent about what's happening with docker and what the implications are. This tool has been under rapid development and is just starting to be useful, so now is exactly the time to start doing that - thanks.

As for the size of images. This is a plague to the entire docker community. On the bright side, with good docker habits (on the side of the image's developer, ie. us), the 0.5GB only needs be downloaded once, as docker layers its images such that updating them can happen cheaply. There are also efforts to use much smaller base images (~50MB), and we hope to adopt those when we have the manpower to rewrite our dockerfiles.

To help clear some confusion, in docker land a container is analogous to a process that is isolated in its own little environment with its own filesystem interface and network stack. However, containers are intended to be stateless, so they can be easily thrown away and updated.  The implication is that in docker land even data gets its own container: a typical service (say tendermint) will have a service container (running the actual tendermint daemon) AND a "data container", that is, a container with the same image as the service (the tendermint docker image), but with no running process. It's purpose is strictly to hold the data. When the tendermint container is started, it is told to use the given data container (`--volumes-from`), and hence can find all its data. `eris data` is a command for managing such containers. So when you run `eris services start tinydns` you'll end up with an `eris_service_tinydns_1` container (running the daemon) and an `eris_data_tinydns_1` container (holding the data). If you then need to do something with the data (inspect, import, export, etc.) you can use the `eris data` command. I wrote a blog post on the concept of data containers: https://eng.erisindustries.com/tutorials/2015/06/17/docker-persistence/

`eris files` on the other hand is an alias for ipfs - it's for adding/fetching files/data to/from the ipfs network. It is wholly separate from the command which manages data containers. Yes, an ipfs service would have a data container, but `eris files` talks to the ipfs container, and the ipfs containers talks to its data container. maybe we could use a better name than `files` ?

Remember, part of the commitment to docker is for setting up these services in the cloud. As we get the image size down, development on mobile will become possible, but until then a mobile dev ought to be ssh'd into a remote box rather than pulling down the images.

Hope that helps clarify. And thanks for pushing us on this.

**Comment by compleatang** [comment]
The confusion between `eris files` and `eris data` is because one of them hasn't had their help updated cause I suspect I copied and pasted and forgot. That definitely needs to be cleaned up.

**Comment by compleatang** [comment]
Clear up text (began) [here](https://eng.erisindustries.com/tutorials/2015/09/05/docker-and-eris/).

We'll add a check step before downloading in #205 .

Short command help cleaned up. 

Gonna close this issue in favor of more precise issues. Please log individual commands for anything in here which we have not captured elsewhere.
