### ISSUE TITLE
chains new flags

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-cli#215]
- [x] `-f` overwrite data folder in `~/.eris/data/chainName`
- [x] publish ports by default, `-p` to not.
- [x] `-r` randomize ports (rejected)

**Comment by zramsay** [comment]
should we flip the default for port publishing on all chains commands?

**Comment by zramsay** [comment]
I went ahead with that, the thinking being that we want as many things "turned on" for new users. Any additional flags that need to be learnt is a barrier to getting things working, imo.

**Comment by compleatang** [comment]
i'm fine with this. i am observing that `-p` will, by default randomize the ports. that is prefered behaviour because without it additional nodes will fail out and someone will only be able to run one chain per machine.

**Comment by ebuchman** [comment]
ok i think the behaviour should be to bind the port by default (same number as internal port, unless specified otherwise), and then if given `-p` it will randomize. but then `--publish` is a weird thing to call it since we will always bind to the host, so maybe `--randomize-ports` or `-r` ? maybe just stick with `--publish` ?

**Comment by compleatang** [comment]
So this issue revolves around two different things really. 

Thing 1. Publishing the exported ports to the host (this was what we did before).

Thing 2. Randomizing the published ports so new users do not have to figure out what the "cannot bind" errors mean (and at some point we're gonna have to control the ports unless we are only ever gonna run one chain per machine (unlikely). 

I'm wondering if we should separate the two functions into their own flags. 

So, `--publish` would *only* publish the exported ports to the host. Then:

* `--api-port` would set the api port in the config and when starting the container export that port (and also publish it if the `--publish` flag given.
* `--peer-port` would work similarly.
* `--rpc-port` owuld work similarly.

Adapting this would require changes in ECM so that it reads the ports from env vars (my prefered manner so folks could use those from chain definition files to change), makes the necessary changes in the config files before booting the executables. 

Having ECM be able to manage the ports will also make it much easier in swarming situations and/or in chains new -N type situations.

What is abundantly clear is that we have to "pass through" the ports in order for the peer advertising to work correctly and the current paradigm where a fixed port is exported but then "routed" through a random port on the host layer will not allow chain nodes to interconnect (they will broadcast to find them on port X, but really from the internet's perspective they are on port Y) so from a functionality point of view the current paradigm is not as effective and approachable as it could be.

**Comment by zramsay** [comment]
point 2 can be dealt with by telling them what the error means and what command to run (`--randomize-ports` or w/e). In general, more verbose error messages I think are a good thing

**Comment by zramsay** [comment]
port stuff dealt with in #245. `--force` added in #268

**Comment by zramsay** [comment]
closed by #268
