### ISSUE TITLE
services exec should work even if process running in container

### ISSUE THREAD

**Issue by ebuchman** [eris-ltd/eris-cli#246]

**Comment by compleatang** [comment]
don't understand this issue. Can you expand on what you mean when you have a moment?

**Comment by ebuchman** [comment]
problem is, if theres a process in the container, exec takes you into that process, rather than a new shell.

**Comment by compleatang** [comment]
Note this is different than #273 which is focused on interactive. but a similar paradigm should be followed here. Instead of actually using `docker exec` we really should be using `docker run` with the data container mounted and whatever we're trying to run given as arg[1] similar to how `data exec` currently operates.
