### ISSUE TITLE
flag for rm volumes (or rm by default)

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-cli#270]
I ended up with 100G of docker volumes; we need be cleaning these up, probably by default (rather than expecting the user to know these volumes will accumulate over time then having to figure out how to delete them)

or, add a flag to `eris services/chains stop -rx ipfs` such that this cmd will remove *everything* related to that instance. This would need to be made clear in the docs. Otherwise, we are bloating users' filesystem (without telling them) & that's not cool

related to #209

**Comment by compleatang** [comment]
:+1:

**Comment by compleatang** [comment]
we need to be careful when we remove volumes as we don't want people to lose their data accidentally. newer dockers (>=1.8) have a volumes API we could probably hook into for some more control if we needed here. 

I'd vote to add this to the `clean` functionality (probably as a flag so its off by default) rather than in `services/chains rm` (which folks will routinely forget about anyway, until they bloat their drives, in which case `clean`)....

**Comment by zramsay** [comment]
in `clean` it is

**Comment by ebuchman** [comment]
what does the volumes api expose that would be useful? also I think we should remove volumes by default, and if its a data container warn the user. otherwise this is just going to be a constant headache for folks ...

**Comment by compleatang** [comment]
k. not sure what the volumes API exposes. Someone would have to look into that (its in go-dockerclient repo)...

**Comment by zramsay** [comment]
https://godoc.org/github.com/fsouza/go-dockerclient#Client.RemoveVolume

**Comment by zramsay** [comment]
or a flag in `RemoveContainerOptions`

**Comment by compleatang** [comment]
OK. So this is breaking into two issues. 

1. Dangling/orphaned volumes (this should be handled by `eris clean`)
2. Remove existing (not orphaned) volumes (flag).
