### ISSUE TITLE
`eris service stop` doesn't always stop a service

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-cli#283]
works fine for `ipfs` and `tinydns` not so much for `mint` or `btcd`

```
Successfully connected to Docker daemon.
Building the Services Group =>	[btcd]
BuildServicesGroup for =>	btcd:0
Loading Service Definition =>	btcd:1
Found Service container =>	btcd:btcd and 1:1
Setting SrvCont Names =>	eris_service_btcd_1:48443f656c1a0f9d30935c61962d33801a1c5bb6f3e87576d3614d9d3f5ce68a
Found Data container =>		btcd:btcd and 1:1
Setting DataCont Names =>	eris_data_btcd_1:4c8ef599be7d58ae22ceb93649b80af264057ae39fbeabd510bb99ef10df308c
Is Service Running? =>		:1
Could not find service cont =>	:1
Service () not currently running. Skipping.
```
probably has (edit: it does not) something to do with #220 & #229

**Comment by pietv** [comment]
@zramsay i've noticed this behaviour too, on Friday. It looks like some definitions have the `name` value defined under `[service]` section like **tinydns**. These work:

![tinydns](http://i.imgur.com/FDkdbDt.png)

And some don't:

![mint](http://i.imgur.com/ZPpFYKn.png)

Maybe insert a condition into the `ServiceFinalizeLoad` function? https://github.com/eris-ltd/eris-cli/blob/master/loaders/services.go#L91-L97 Something like
```go
// If no service name, use definition name.
if srv.Service.Name == "" {
    srv.Service.Name = srv.Name
}
```

Why the `StartService` always works, and `KillService` doesn't is because the former uses the `ops.SrvContainerName` value to start the container and the latter uses `srv.Service.Name` to stop one.

**Comment by zramsay** [comment]
ah good catch. thanks - that speeds up the debugging :)

**Comment by pietv** [comment]
cool :)

**Comment by zramsay** [comment]
@hartct this is the issue you identified. fix in progress. temporary workaround is adding `"name"` under `[services]` in the definition file
