### ISSUE TITLE
eris services personal/dependencies file store

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#288]
**problem** I want to be able to formulate service definition files which may have some private stuff in them and / or are personal. Currently these would be overridden whenever I init or update because of the git pull. 

**solution** Personal stash of service definition files which can be used. I would suggest we use `~/.eris/services/personal` but am open to other people's ideas.

This paradigm could also be used in the future when we do projects because we could then move services into and out of scope depending on which project was checked out. So it could be `~/.eris/services/PROJECTNAME` or something like that.

**Comment by zramsay** [comment]
This makes sense to me now. I like the idea of having projects in subfolders so you can have your servDef files grouped ... and then `checkout` projects (I can imagine `~/.eris/services` getting bloated with time, too, so it would be nice to split things up a bit)

Will include it as part of #309. Closing since for now all this will do is drop an extra dir in `/services`, and is made somewhat less relevant by the init refactor anyways.

**Comment by zramsay** [comment]
re-opening since it missed the boat on init refactor. Solution will include `~/.eris/services/personal` & `~/.eris/services/dependencies`; the latter (and maybe former??) for deps not listed by `eris services ls --known`

**Comment by zramsay** [comment]
recently added. closing for now. not sure about `dependencies` just yet
