### ISSUE TITLE
build namespaced genesis and config stash within ~/.eris/blockchains

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#34]
(useful for testing purposes as well as for baas type situations).

this should be globally configurable reference to a specific file.

a base specific file should be compiled into the binary (like we do with erisdb and ipfs service definition files).

perhaps a default genesis.json repo (to mirror services and action repos) could be pulled in during Initialize.

**Comment by dennismckinnon** [comment]
I like the idea of constructing a base file. since the genesis must have the account inserted though i doubt we can put these in a dedicated repo unless you just want the configuration settings copied. I think we probably can be more opinionated then that. someone can edit their default if they want but we should set the settings. fast_sync off for instance.

**Comment by ebuchman** [comment]
i like the default behaviour being that it serves you a fresh genesis.json with the corresponding new key, so you can start running a one man chain right away. any predetermined genesis.json that correspondings to a running chain would be `fetch` (now known as `install`).

**Comment by compleatang** [comment]
good point re the repo. we could use a `~/.eris/blockchains/genesis` directory and then have `caseythrowaway` in there. then we can use `eris chains new --genesis caseythrowaway asdf1234` that would use `~/.eris/blockchains/configs/default.toml` as the config.toml and `~/.eris/blockchains/genesis/caseythrowaway` as the genesis.json and spin up the container; alternatively `eris chains new asdf124` would use `~/.eris/blockchains/genesis/default` as the default (fresh) genesis.json.  

note, none of this would conflict with either of your points (I don't think)

**Comment by ebuchman** [comment]
so i think the only thing this buys us is determinism re your address for testing contract systems that require hardcoded addresses (which is bad design anyways)

but it also buys a standard spot for genesis.json files, which is great, because we can cache them there too as we fetch em from etcb in our various adventures.

however I still like the default behaviour (no genesis specified) to be a fully fresh one with a new key and no default persistence (besides the data container).

**Comment by compleatang** [comment]
OK. I'm happy with that default.

To be clear, I think we should have a standard spot for both genesis and config's although I think configs probably will just be the default....

**Comment by ebuchman** [comment]
```
.eris/
  config/
    ipfs/
       ipfs.conf
    mint/
        config.toml
    ...
```
?

**Comment by compleatang** [comment]
i was thinking more like:

```
.eris/
  blockchains/
    chainA.toml
    chainB.toml
    genesis/
       throwaway1.json
       composing.json
       composed2.json
   config/
       default.toml
```

services configs should mostly be done via env vars when possible.

**Comment by compleatang** [comment]
that said, i'm not adverse to a configs folder a level higher.

**Comment by ebuchman** [comment]
cool im into that

**Comment by compleatang** [comment]
with `--dir` am wondering if this is necessary at all. thoughts?

**Comment by compleatang** [comment]
Zach, bumping this over to you. I think we've moved on a bit so what would be good is now that we have `--dir` that we can just give it a name and if that name isn't a path that matches we check `~/.eris/blockchains/config/NAME` and use that if it exists. So someone can:

**Comment by zramsay** [comment]
everything in `NewChain()` has been commented out (except for returning `setupChain`). I'm hesitant to muck about in the latter ...

**Comment by compleatang** [comment]
np.
