### ISSUE TITLE
error dumping

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#403]
docker-machine recently did this...:

```
Error Reporting

As part of our continued effort to make the Docker Machine experience better, we have added some behavior which will report various kinds of failures to Bugsnag for the core maintainers to debug.

In most cases this should happen in the background without needing any input or action from the user. If you wish to opt out of this error reporting, you can create a no-error-report file in $HOME/.docker/machine, e.g.:

$ mkdir -p ~/.docker/machine && touch ~/.docker/machine/no-error-report
```

That may be a smart idea for us. Potentially, when a user encounters and error it would automatically send a notification to bugsnag, with the full debug output (assuming we'd flush the debug level logs, perhaps to a different writer...?). 

This may be connected to the move to logurus.

For reference:
https://bugsnag.com/docs/notifiers/go

**Comment by pietv** [comment]
Great! I like the idea. Docker Machine's implementation looks very clean too.
At first we're likely interested mostly in crashes (panics)?. Since this is an experimental tool, there'll be many errors, including Docker API ones...

Something like `ERIS_CRASH_REPORT=false` can prevent the sending of it when running the tests, for example.

Since the eris-cli is a tool, not a service, it'll be safe to keep the debug log in memory to be ready to flush it at panic.

:+1:

**Comment by compleatang** [comment]
Relatedly:

https://github.com/Shopify/logrus-bugsnag/blob/master/bugsnag.go

or 

https://github.com/polds/logrus-papertrail-hook

The move to logrus really should make this quite easy. We'll want this to be optin in the Global Config (eris.toml) and we should ask users during `eris init` if they would like to optIn to help us with our stability or whatever folks say to such messages. 

I think for testing it may make sense to dump all errors to papertrail. That will help our debugging since we already have an account there and it is a pretty good service. We may want user errors to get routed to bugsnap (which I've not looked into, but docker-machine at least uses) or another similar service (logrus has numerous options)....

**Comment by pietv** [comment]
Yeah, it should be very easy because in all case it'll be very similar — just adding one line to client code to add a hook. There can be multiple hook to select from simultaneously.

Alternatively it can be Sentry which has a nice Go client library with it (https://github.com/getsentry/raven-go) or AWS Lambda?

I wil go with Papertrail first — to test user / our experience with this.

**Comment by compleatang** [comment]
I'm not tied to any of the services (sentry, papertrail, etc.).

**Comment by compleatang** [comment]
closing. This is ready for 0.11.3
