### ISSUE TITLE
[Q] How to monitor an eris:db server?

### ISSUE THREAD

**Issue by alexandrev** [eris-ltd/eris-cli#419]
I'm writing an evaluation report about the eris blockchain solution and I'm trying to know if does it exist a tool / project / component to monitor the eris:db server? I'm looking for something similar the ripple-frontendcharts component 

How do you monitorize the chain? Using standard docker tools?

Thanks in advance

**Comment by compleatang** [comment]
We have a rudimentary api which is available at http://ip:rpc_port/rpc and we have a set of js wrappers for doing more complex things at eris-db.js and eris-contracts.js. These connect into the `api` port at ip:1337.

Smart contracts chains are very different than transactional chains in how they are monitored because there is much less emphasis on the tx's and much more emphasis on the state of the storage in the contracts (where data is usually "held"). 

The path issues should be mostly fixed now, BTW.

**Comment by alexandrev** [comment]
Thx @compleatang. I understand it. I close the issue since my question is answered :)
