### ISSUE TITLE
remote commands

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#447]
- [ ] machines (up or down)
- [ ] new
- [ ] rm

remote definition files schema:

* provider
* data centers
* machines

**Comment by zramsay** [comment]
Proposed functionality for v1 `remotes`: 

`eris remotes new NAME NUM` => writes remote definition file to `~/.eris/remotes/name.toml`  and NUM = # of nodes to launch. Includes also bullet points above (driver, region, etc). Strong opinion: A remote is collection of hosts and the `remotes` command is directed towards operating all those hosts as a coherent group. The idea is to have clusters of remotes that do specific things, rather than a single remote that has hosts doing all kinds of things.

`eris remotes init/create NAME` => provision NUM cloud instances with name scheme `eris-remote-NAME-1` similar to our container naming schema.

`eris remotes ls` => would adopt similar schema to current ls functions (listing known/existing/running remotes...which is great cuz a remote can be of each one of those types:) ). To list all the hosts of a remote: `eris remotes ls NAME`

`eris remotes do NAME ACTION` => where an action is a pre-defined series of `eris` commands (or other?) that will be executed on all hosts of that remote. We're gonna want a `--remote` global flag too (which will to some extent replace `--machine`).

`eris remotes rm NAME` => destroy all hosts of that remote
`eris remotes start/stop NAME` => self-explanatory

Since a remote can have a single host (machine), there's no need for #446.

**Comment by compleatang** [comment]
> The idea is to have clusters of remotes that do specific things, rather than a single remote that has hosts doing all kinds of things.

**Comment by compleatang** [comment]
based on direction of dm, think it best to close this issue for now. We can revisit it later if functionality is necessary for us to capture. Right now we probably aren't adding much value with `remotes`.
