### ISSUE TITLE
chains new should only new a chain, not start it

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-cli#474]
For consistency with `services | remotes new` which only lay a `.toml` file. The pipeline would then be `chains make`, `chains new`, `chains start`. It's an extra cmd but well worth it I think. Right now, we completely obfuscate the laying of that file (basically a service definition), which does a disservice to users.

In addition to laying the toml, `chains new` could have some pre-start checks to ensure things are in order. Might want this option to be chatty (i.e., output all the things it's checking) which could be really helpful to users. 

Related to demonstrating "how-to-chain" with only services.

can block on #459 and #336

**Comment by compleatang** [comment]
I think we should open this up to a user question and get some feedback.

**Comment by compleatang** [comment]
Am not sure about this issue. It does map nicely to `services new` I agree. However it almost seems like an irrelevant step. We could make the chains definition file with make, but what new does WRT to chains is slightly different than the problems services new is trying to solve. 

`new` currently should be doing three things:

* make the chain definition file (could be moved to make if we wanted this isn't terribly important to be in new)
* copies the relevant chain files into the data container
* starts the chain

The biggest difference here is the middle bullet. If we refactor new to not start the chain we will still need new to do at least the last two bullets. 

There are some advantages to the current approach, though. I will say that when working on debugging and resetting chains it is fast to just `eris chains stop -rxf chainName && eris chains new chainName --dir dirName && eris chains logs -f chainName`. Adding an extra step in there would be more typing for not necessarily less cognitive overhead (because there is the difference of copying the relevant files into the dataContainer that differs between services and chains).

**Comment by compleatang** [comment]
All in all, this is probably something worthwhile to gain user feedback on.

**Comment by zramsay** [comment]
closing for now. can re-visit later if need be. we don't want to be adding an extra step & confuse ALL the users who use `chains new` to get going. this would also break a tons of `.sh` across many repos

**Comment by zramsay** [comment]
to be clear, i'm assuming the user feedback would be "why the heck would i want to type an extra command"
