### ISSUE TITLE
docker version not parsed properly: 1.10 should be greater than 1.8.

### ISSUE THREAD

**Issue by furiousOyster** [eris-ltd/eris-cli#493]
This commit introduces a bug for those on docker v1.10.
https://github.com/eris-ltd/eris-cli/commit/5ba80c2daee690dc49d8a72508807c13052685e4

The resulting float64 is 1.1, which is crucially < 1.8

suggest storing comparison as string, or as array of major minor perhaps ?

**Comment by compleatang** [comment]
Thanks for this. We'll get a fix out tonight, latest tomorrow morning.

**Comment by pietv** [comment]
hi @furiousOyster, the fix for this issue is implemented in the #eris_version branch, it'll be merged with the #develop branch later (likely tomorrow), i'll then let you know.

If you'd like to have the fix sooner, you can pull that branch and rebuild the binary like this:

```
$ git fetch origin eris_version
$ git checkout eris_version
```
and then from the `eris-ltd\eris-cli` directory:

```
$ go clean -i ./cmd/eris
$ go install ./cmd/eris
```

We have a neat `eris update --branch eris_version` shortcut command for the above, but you won't be able to use it in your case.

Thanks for reporting the issue!

**Comment by pietv** [comment]
The fix is in the #develop branch now.

**Comment by furiousOyster** [comment]
Works on ubuntu-14-04 with docker version 1.10.0, go version 1.6rc2, eris CLI version 0.11.2 from #develop.

**Comment by pietv** [comment]
Great! Thank for the feedback and the details.
