### ISSUE TITLE
Creating new chain with different port

### ISSUE THREAD

**Issue by kootenpv** [eris-ltd/eris-cli#508]
Following https://docs.erisindustries.com/tutorials/advanced/servicesmaking/ after having made a simplechain before.

What is strange is that using:

    eris chains new bob --dir $HOME/.eris/chains/bob --verbose

I'd expect it to use settings of `config.toml`, where I changed the ports. But I'm getting a 

    API error (500): Cannot start container eris_chain_bob_1: failed to create endpoint eris_chain_bob_1    on network bridge: Bind for 0.0.0.0:46657 failed: port is already allocated

regardless.

Is this supposed to be like that?

**Comment by compleatang** [comment]
This is expected behaviour. When you change the config.toml that indeed does change the port which the erisdb node is talking on, but the error you're experiencing is actually about how docker starts the containers.

There are two ways to deal with this issue. The first is to change the port in your chain definition file (which is how eris tells docker to start the containers). In the `[service]` portion of your bob.toml add a line which looks like this:

```
ports          = [ "1338", "46658", "46659" ]
```

(or whatever ports you want to use).

The second way is to use the `--publish` flag. This is not a very well described name frankly, but we use it to reduce confusion (its docker's terminology). That flag will provide random ports on the host to use. 

When quickly prototyping we generally use the `-p` flag (short form for `--publish`) tactic and then once we've stabilized we use the chain definition file tactic.

**Comment by kootenpv** [comment]
It's clear, useful to hear about the two tactics.
