### ISSUE TITLE
collapse `eris ls`

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#536]
**Problem** -- Users need to have a clear picture of `eris` at any one time. Basically my "dashboard" on the command line for what is happening with eris. We've built this functionality for the most part as `eris ls`. But what is outputted is (a) hard to quickly understand; (b) broken into too many pieces; (c) too long (unless I'm running an insanely large deployment it should not require me to scroll in my terminal window).

**Solution** -- Proposing a few specific UX changes to address this:

- [x] remove `--known` completely. As we gain in sophistication this is growing longer, but it isn't really helpful at all to users for what `eris ls` is trying to do. Indeed, I would advocate we should totally remove `--known` from all the listing functions but *only* expose them as `eris services ls --known`.... 
- [x] data containers which match to a service|chain container should not be displayed in `eris ls` (rather it should be a Yes|No in the output table immediately following `running` field). data containers which do not match to a service|chain container should be displayed
- [x] query... and i'm not sure. whether ports field is relevant (it probably is, but if folks feel strongly that it is not relevant information have no problem removing it as unnecessary cognitive load)
- [x] version information. `docker ps -a`'s image field is sometimes important for having an understanding (like is chainX running erisdb:0.11.2 or 0.11.3 or whatever) of what software the underlying binary for the service|chain is running. since eris' best practice is to utilize docker image tags here we should leverage this good practice to simplify the necessary information for users. i.e., we should display a `version` that maps to the docker image's tag. I would propose this field is placed between the `machine` and `running` fields in the current table.
- [x] remove actions from eris ls
- [x] vertical ordering should not be `chains` then `services` (as is current) but rather `services` then `chains` (with data only displayed if there are data containers which don't match to services/chains)
- [ ] add new field (the `autodocker` field) before container name. this will become more necessary as we have to plug more things "into" docker's daemon (e.g., obc, etc.). links to #472

**Comment by zramsay** [comment]
++
like the data field. think we should keep ports - it's quite useful. agree `eris ls` should look more like `docker ps -a`

**Comment by pietv** [comment]
A small heads-up how the output of the `eris ls` command will look like:

```
   SERVICE     CONTAINER NAME   DATA CONTAINER
*  logrotate   ipfs-07cd8e87    ipfs-849004ce
*  tinydns     ipfs-5de63933    ipfs-40000e98
*  keys        ipfs-db040e8d    ipfs-ee980980          
 
   CHAIN       CONTAINER NAME   DATA CONTAINER
*  ab          ipfs-7fa5853a    ipfs-3e224870  
```

The `*` symbol is a recognized mnemonic for a changed file (for example in `emacs(1)`) or something active (as in `fdisk p`, `sfdisk -l` commands outputs or with the Microsoft's `diskpart` utility print out for bootable partitions).

The data container status is replaced for referencing directly the container instead of the `yes` word because you'd still need to reference the data container name somewhere if you don't in the `DATA` section of the `eris ls` output.

The `CONTAINER NAME` / `DATA CONTAINER` inconsistency is retained on purpose (because `CONTAINER NAME` is more obvious than the simple `CONTAINER` and `DATA CONTAINER` is cleaner than the `DATA CONTAINER NAME`, arguably.


Alternatively, the plain `eris ls` output with the `STATE` column istead of the `*` symbol:
```
SERVICE     STATE     CONTAINER NAME   DATA CONTAINER
logrotate   running   ipfs-07cd8e87    ipfs-849004ce
tinydns     running   ipfs-5de63933    ipfs-40000e98
keys        running   ipfs-db040e8d    ipfs-ee980980
 
CHAIN       STATE     CONTAINER NAME   DATA CONTAINER
ab          stopped   ipfs-7fa5853a    ipfs-3e224870
```

Both outputs should likely fit the 80-column terminal width (likely because the width is dependent on the service or chain name length).

**Comment by pietv** [comment]
The `-a, --all` flag (extended output) is introduced to output the remaining informative fields (which altogether won't fit the 80-column width): the `MACHINE`, `PORTS`, 'IMAGE`, `COMMAND`, and `AUTODOCKER` values.

The `-a, --all` flag name is an allusion to the `ls -a` and `docker ps -a` flags.

**Comment by compleatang** [comment]
`*` paradigm has my vote as its cleaner...

**Comment by compleatang** [comment]
`-a` flag good choice imv.

**Comment by pietv** [comment]
The `-f, --format` flag can override any other outputs with the specified template, for example:
```
$ eris ls --format='{{.Name}} {{.Running}} {{.Data}}'
```
will yield this output:

```
logrotate true true
tinydns true
keys true true
ab true true
```

The `-f, --format` flag behaves the same way it does for the `go list` or `docker ps --format` commands, since the `eris ls` is implemented with the Go templates.

The `-f` flag is useful when you need specific values in the output and don't want to resort to `cut(1)` or `awk(1)` commands for filtering.

**Comment by pietv** [comment]
The `-q, --quiet` flag will be replaced with the `--json` flag since it better communicates the purpose what it will output (for all `ls` commands).

**Comment by pietv** [comment]
The `--known` flag output will list the files in the respective definitions files the way the `ls` command does in the multi-column mode:

```
$ eris services ls --known
bigchaindb.toml      compilers.toml   keys.toml        openbazaar.toml  tor.toml
bitcoinclassic.toml  do_not_use.toml  logspout.toml    rethinkdb.toml   watchtower.toml
bitcoincore.toml     eth.toml         logsrotate.toml  tinydns.toml
btcd.toml            ipfs.toml        mindy.toml       toadserver.toml
```

```
$ eris actions ls --known
chain_info.toml  dns_register.toml  do_not_use.toml  keys_list.toml
```

Again, this can be overridden with the `-f, --format` flag:
```
$ eris actions ls --known --format='{{,Name}} {{.Definition}}'
```
where `Name` differs from the `Definition` output that the latter has the `.toml` suffix.

**Comment by pietv** [comment]
All above formats can be easily overridden since they're implemented with the templates. Please, kindly speak out if there are any inconsistencies, idiosyncrasies, annoyances so that they can be fixed faster. Thanks.
