### ISSUE TITLE
Make docker package dependency in debian control more flexible

### ISSUE THREAD

**Issue by step21** [eris-ltd/eris-cli#542]
Hi, so I originally installed docker from the docker repo, as you recommend, but turns out in the meantime they switcher their repo and the packagenames. This means although I had docker 1.9.1, it was not recognized as a valid dependency, as the package was called docker.io
It is also not that obvious, as the repo link does not give 404 but a textfile, so unless you check your apt-get update manually ... Maybe it would help to put a note about this in the documentation?

**Comment by compleatang** [comment]
This is helpful. Thanks! Happy to add into our documentation but I want to make sure I precisely understand the situation. (We'll also update our debian control files if we need to).

My understanding is your baseOS is ubuntu-trusty and you apt-get installed eris but when you did so it had a requirement for docker which was not being satisfied because you did not install docker via apt-get, can you confirm that? 

(It's a common enough pattern which should not create any friction for getting running so am anxious to fix.)

**Comment by step21** [comment]
Situation: Base os Ubuntu Trusty 14.04.04 If docker was installed from another source (old docker.com repo or lxc-docker from ubuntu or another from some ubuntu cloud ppa) you have the right docker version but the package name is different so that the eris package will not recognize it. So I still used apt-get to install docker, just from a different repo. These might be from the same source with just different names or be originally for different configurations, I am not really sure.

See for some more info on versions:

http://www.ubuntuupdates.org/package_metas?utf8=%E2%9C%93&q=docker.io
http://www.ubuntuupdates.org/ppa/docker?dist=docker

**Comment by compleatang** [comment]
Awesome summary thanks. We'll make sure that dependency in the debian control file captures this. cc @pietv

**Comment by step21** [comment]
Thanks. :)

**Comment by pietv** [comment]
Hi @step21, the issue should be fixed in the latest (0.11.3) `eris` package version. 

If this issue is still relevant for you, please try updating the package from this repo:

```
deb https://apt.eris.industries trusty main
```

or by downloading it directly from Github: https://github.com/eris-ltd/eris-cli/releases/download/v0.11.3/eris_0.11.3_amd64.deb

Thanks.

**Comment by compleatang** [comment]
Closing for now. Step feel free to reopen if it's not fixed.
