### ISSUE TITLE
`eris init` misidentifies Docker version and refuses to run.

### ISSUE THREAD

**Issue by NodeGuy** [eris-ltd/eris-cli#546]
I'm following the tutorial here: https://docs.erisindustries.com/tutorials/getting-started/

```
$ go get github.com/eris-ltd/eris-cli/cmd/eris
$ eris init
Eris requires docker version >= 1.8
The marmots have detected docker version: 1.1
Come back after you have upgraded and the marmots will be happy to service your blockchain management needs
$ docker --version
Docker version 1.10.2, build c3959b1
$ eris version
Eris requires docker version >= 1.8
The marmots have detected docker version: 1.1
Come back after you have upgraded and the marmots will be happy to service your blockchain management needs
```

I ignored the following tip because I don't want "new stuff", I want stability:

> Tip: To see all the new stuff happening:
eris update --branch develop

**Comment by pietv** [comment]
which way did you install the Eris. `go install` or binary package `apt-get`?

**Comment by NodeGuy** [comment]
`$ go get github.com/eris-ltd/eris-cli/cmd/eris`

**Comment by pietv** [comment]
The issue is not reproducible on Linux with Docker v1.10.2 and the installation via the `go get` command.

Did you try cleaning up the previous `eris` binaries with the `go clean -i github.com/eris-ltd/eris-cli/cmd/eris` command and running the `go get` again after that?

And making sure the the binary in PATH is the one installed?

Thanks for reporting the issue.

**Comment by NodeGuy** [comment]
> Dave, could you please try to have a recipe for your bug first? because right now it seems (to me) like you have a "stale" binary.

Let's assume that's true.  I don't know how to recreate that but I'm willing to try if you give instructions.

**Comment by NodeGuy** [comment]
> Did you try cleaning up the previous eris binaries with the go clean -i github.com/eris-ltd/eris-cli/cmd/eris command and running the go get again after that?

```shell
$ go clean -i github.com/eris-ltd/eris-cli/cmd/eris
Davids-MacBook-Pro:~ david$ go get github.com/eris-ltd/eris-cli/cmd/eris
Davids-MacBook-Pro:~ david$ eris init
Eris requires docker version >= 1.8
The marmots have detected docker version: 1.1
Come back after you have upgraded and the marmots will be happy to service your blockchain management needs
```

**Comment by NodeGuy** [comment]
> And making sure the the binary in PATH is the one installed?

It looks like it is:

```
$ which eris
/Users/david/Documents/Toptal/clients/Eris/gocode/bin/eris
Davids-MacBook-Pro:~ david$ echo $GOPATH
/Users/david/Documents/Toptal/clients/Eris/gocode
```

**Comment by compleatang** [comment]
This is fixed.

**Comment by primehat23** [comment]
I am having the same problem.
docker version: 1.11.1 ect.... 
eris init: eris docker-machine version >=0.6.0, the marmots have detected docker-machine version 0.7.0 blah blah....
I'm using babun and I used the babun-docker-update from a GitHub repo and says its up to date. So how did you solve this my good chap?

**Comment by pietv** [comment]
hi @primehat23, thank you for reporting the issue! Are you seeing this on Windows or some other OS?

There's a ticket #700 opened for this particular issue and for the moment I believe it should be solved. The fix is in the #develop branch or in a compiled binary mentioned in the comments. Please, let me know if the fix works for you. Thank you.

**Comment by pietv** [comment]
Ah, babun -> windows, gotcha.
