### ISSUE TITLE
install README should instruct users to install binary, not via go

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-cli#547]
installing eris via go should be reserved for developement

**Comment by compleatang** [comment]
Disagree with this issue.

The README will be read by developers and as such I'd prefer to keep it as is. Developers who are uncomfortable with go should be routed to getting started where we cover binary installation in deeper detail.

If we want to emphasize binary installation in the documentation that is not a problem from my POV but we should handle in docs site rather than here.

**Comment by compleatang** [comment]
split the baby here.
