### ISSUE TITLE
harmonize go/docker/dm versions across CI platforms

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-cli#582]
each circle/travis/appveyor lack harmonized version control for these installs

can a GH repo have global vars?

**Comment by compleatang** [comment]
The only way I know to do this would be to have a little csv file in the root of the repo and then have the ci.yamls `$(cat ... | grep XXX | cut -d ',' -f 2)` it... Not sure if that would even work, but may be worth giving a try. 

If something doesn't work against one OS we can manually change it until the bug is fixed...

**Comment by compleatang** [comment]
closing for now as Jenkins should solve this with build AMIs.
