### ISSUE TITLE
Allow specifying an explicit port for chains start command

### ISSUE THREAD

**Issue by j-h-scheufen** [eris-ltd/eris-cli#592]
It is currently not possible to explicitly set an exposed port for the chain container (except for default 1337). This should be possible via a command line parameter.
The only option when running multiple chain containers is "-p" to randomize ports, but this leads to unreliability when running multiple chains and having to change port configurations in applications or scripts after restarting a chain.

An ideal scenario would re-use the existing "-p" parameter and allow it to be optionally followed by an integer such that:
- `eris chains start xyz -p` randomizes the port (existing behavior)
- `eris chains start xyz -p 34343` exposes RPC port 34343 to the host

**Comment by compleatang** [comment]
Note, that we would need a comma separated list of all three ports to do this properly. 

In the alternative we can just set one port (which would be tmintRPC) and then (tmintPeer and edbRPC) ports would be +1 and +2 respectively. 

Moving in this direction would require a change in that flag type. Indeed, we may want to revisit #338 . Or not.

**Comment by pietv** [comment]
Since it's `-p`, it could be renamed to `--ports` which makes sense.

:+1: for comma separated lists and autoincrementing ports. Additionally it could use mapping like `-p 46657:60000` if you'd like to reassing "the second" port from the list only.

(As for partial randomization of ports — until it's really needed, probably doesn't worth implementing.)

**Comment by pietv** [comment]
@j-h-scheufen I'm adding the additional flag `--ports` for specifying the port accessible from the host.
The boolean flag `-p` cannot be reused as a "string" flag. This is a deficiency (feature) of the Cobra flag parsing library and the Go built-in `flag` package which Cobra mimics.

The `--ports` syntax is the following:

* `--ports 14000` — map the exposed port from the definition file to a new published port.
* `--ports 14000,15000,16000` — map a list of exposed ports from the definition file to a list of published ports.
* `--ports 50000:46656` — map a specific exposed port (46656) to a specific published port (50000).
* `--ports 14000-` — map all exposed container ports from the definition file to ports starting with 14000 (incrementing by 1).
* `--ports 15000,50000:46656,17000-` — a mix.

Examples:

```
$ eris chains new simplechain --ports 14000

  PORTS
  0.0.0.0:46656-46657->46656-46657/tcp, 0.0.0.0:14000->1337/tcp

$ telnet localhost 14000
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.

$ eris chains new simplechain --ports 50000:46656

  PORTS
  0.0.0.0:1337->1337/tcp, 0.0.0.0:46657->46657/tcp, 0.0.0.0:50000->46656/tcp

$ eris chains new simplechains --ports 9001-

  PORTS
  0.0.0.0:9001->1337/tcp, 0.0.0.0:9002->46656/tcp, 0.0.0.0:9003->46657/tcp

```

The `-p` flag overrides the effect of the `--ports` flag.

Note: `eris chains start --ports` behaves just as the `eris chains new --ports` ports-wise, but the chain shouldn't exist when it is started with `--ports` (since the `-p` and `--ports` settings are stored within the container, so they don't have effect if the chain container already exists).

Please, test this new feature whenever you can (by fetching the `flexible-ports` branch). I will merge it then.

**Comment by pietv** [comment]
The feature now is in the #develop branch.

**Comment by j-h-scheufen** [comment]
@pietv for some of the defined use cases the feature works as expected, but for others there seem to be issues. Example: Port ranges work great, but this scenario did not:
```
$ eris chains new test7 --ports 7550,6556,8789
<nil>
Error moving keys: API error (500): Could not get container for eris_chain_test7_1
```
I also managed to end up with multiple chains with the same name when
a) removing all containers from an existing chain
b) starting the chain with different --ports options

Should I collect findings in a separate ticket?

**Comment by pietv** [comment]
@j-h-scheufen thanks for taking the trouble for testing this. there's an issue with splitting port list separated by commas, a temporary solution would be to separate the ports with spaces like this: `eris chains new test7 --ports "7550 6556 8789`, but I will get back to you with a proper solution quick. I have a  case for this, but it tests cases after splitting.

Please update to the #develop branch so that we'll be on the same page.

> I also managed to end up with multiple chains with the same name when
I don't fully understand what this means. Do you have maybe an example with a sequence of commands. Thanks.


.

**Comment by pietv** [comment]
Please use the #fix-flexible-ports for testing.

**Comment by pietv** [comment]
@j-h-scheufen may I close the issue?
