### ISSUE TITLE
[Core] Allow init to pull from tarball repositories using `docker load` equiv

### ISSUE THREAD

**Issue by Latrasis** [eris-ltd/eris-cli#611]
Currently when setting up an eris node, pulling from quay.io requires approximately 4-6 min. We have thought of using a cache instead to spead up the process. Is there any way to have eris use a custom url for image pulling? (Other than overriding DNS)

**Comment by zramsay** [comment]
the tool will spillover to pulling from dockerhub if there's a problem pulling from quay. that's not really a solution to this problem. we have an open issue to use alpine rather then ubuntu for the base image, which will help. we also recommend using docker-machine to spin up nodes in the cloud, this avoids pulling to a local machine (which is much slower). i'm also looking into how `docker save/load` can be used to simplify the process.

**Comment by zramsay** [comment]
by "simplify the process", reduce the pull time somehow

**Comment by zramsay** [comment]
++ on the re-named issue. great idea. related to an issue (can't find it) that would pull the Dockerfile from ipfs and build service image on the spot.

**Comment by compleatang** [comment]
yes. i'd love to build a little tool that will do that. ... someday.

**Comment by AFDudley** [comment]
Here is a pattern for reducing actual on disk size of docker containers, the solution is imperfect because we lose the savings from layers. Other techniques can be applied to retain the layer savings but that is somewhat out of scope at the moment.

> docker build -t test-me .
docker run --name export-me test-me
docker export export-me | docker import - test-me:exp-me
docker rm export-me
docker push test-me:exp-me

**Comment by zramsay** [comment]
closing given that added complexity of this feature & the (now) significantly reduced docker image sizes
