### ISSUE TITLE
[Chains] eris chains new => eris chains start && some other cleanup of chains

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#651]
**Problem** -- there is some cognitive overhead around "how we make the files I need to turn the thing on". For the services stream this is usually `eris services new`. For the chains stream this is usually `eris chains make`. For the upcoming remotes command this should be `eris remotes make`. 

**Solution** -- Two steps we could do to simplify this. One of which I'm keen to do, the other I'd like feedback. 

First, we should move `eris services new` -> `eris services make`. Since new on chains does something that goes vroom, new on services just drops some files, and eris chains make just drops some files, the first way we should harmonize is just to change services new to services make. 

Second, and the one I'm not so sure about, is to then collapse the chains new|start into one. Right now there is significant overlap between these two which could potentially be reduced. That said, there is the importing data part of chains new which is different and unique from how we do services (where we don't assume there will be a data import). All in all, I'm modestly against collapsing new and start for chains, because I do think these are distinct enough to handle the cognitive overhead of two commands vis a vis one.

**Comment by zramsay** [comment]
++ on first. WRT to the second, i'd suggest we poll our users though i'd also be in favour of it

**Comment by zramsay** [comment]
i'm gonna go ahead and `services new => services make` so that we can start getting used to that over the next few weeks. another thing we should consider since it's been discussed is to put the ipfs/keys servDef files into the binary. keys for sure since it'll soon be versioned & we don't want to version bump servDef files on toadserver every release

**Comment by zramsay** [comment]
closed by #713. we can revisit collapsing `chains new/start` if need be but for now i'm also fairly against it

**Comment by zramsay** [comment]
clear need to revisit this issue. cc @AFDudley @SCBuergel

**Comment by compleatang** [comment]
My proposal ...

![blank diagram - new page](https://cloud.githubusercontent.com/assets/590037/16764531/f8816382-482e-11e6-8eba-e46d3de01d03.png)

**Comment by zramsay** [comment]
agree on all of it except that `chains start` without `--init-dir` would `chains make --chain-type=simplechain` (then presumably start that simplechain) per the bottom box. Reasoning: not running `make` for creating new chains would be a bad habit for users, even if for a simple chain (IMO). since it's been brought up that we should have a quick and dirty get way of getting going, might I propose: `eris go` that does a ton of stuff...essentially setting the user up & stopping short of `node app.js` in the contracts interacting tut. I don't have super strong opinions here tho.

**Comment by zramsay** [comment]
we might also want to sort out what to do with `eris chains new(start) default` & the `ThrowawayChain()` function. there's some duplication there that ought to be dealt w/ (deprecated) and/or documented.

**Comment by zramsay** [comment]
- [ ] deprecate `chains.KillChain(do)` => this function has overlap (& less fine-tuned) functionality with `chains.RemoveChain(do)`

**Comment by zramsay** [comment]
currently blocking on #878 (removing `--file` from `eris chains rm` & cleaning up that process altogether...the chain definition file has proven the trickiest part of finishing up this consolidation.

**Comment by zramsay** [comment]
- [ ] eliminate chainID

**Comment by zramsay** [comment]
this:
```
eris chains make library_chain --account-types=Root:2,Full:1 simplechain
```
is problematic. I've seen it in two tutorials written by external folks and should not fly. The doc/tut that they're getting it from also needs to be fixed.

**Comment by zramsay** [comment]
this can be closed...specific issues/bugs with the implementation are in their own issues
