### ISSUE TITLE
Eris does not run with Docker for Mac

### ISSUE THREAD

**Issue by roderik** [eris-ltd/eris-cli#683]
the cli expects a VM to be running, but under Docker for Mac it is not.

https://gist.github.com/roderik/020f1fb707dcfbd44caced79c1f61bce

**Comment by VoR0220** [comment]
What version of OS X are you running?

**Comment by zramsay** [comment]
hi @roderik, thanks for the issue. Prior to Docker for Mac/Windows, we've required `docker-machine` to run eris. Until #684 is implemented, you'll have to use `docker-machine` for these two OSs with eris. See [our tutorial on the tool here](https://docs.erisindustries.com/tutorials//tool-specific/docker_machine/) for more information.

**Comment by pietv** [comment]
hi @roderik, i second that using the `docker-machine` on MacOSX is better for now because that link is better tested. In the meantime, if you're keen to try please fetch the `beta-docker-fix` branch in which the fix is and which doesn't make Eris expect a VM to be running.

If you installed Eris using `go get`, please run the command `eris update --branch=beta-docker-fix`

If you installed Eris by downloading a binary, please set `GOPATH` (anywhere) and `GOBIN` (somewhere your PATH points to) and run:
```
$ git clone https://github.com/eris-ltd/eris-cli
$ git fetch origin beta-docker-fix
$ git checkout beta-docker-fix
$ cd eris-cli/cmd/eris
$ go install
```
Thanks!

**Comment by pietv** [comment]
@roderik may I close the ticket?

**Comment by pietv** [comment]
Merged to #develop.
