### ISSUE TITLE
 Older Eris repository not working? (from Roll Your Own Blockchain docs)

### ISSUE THREAD

**Issue by BlockChanger** [eris-ltd/eris-cli#775]
When I tried this: (from: https://docs.erisindustries.com/tutorials/getting-started/ "Step 2:  Roll Your Own Blockchain in Seconds)

`eris chains make test_chain --chain-type simplechain`

It freezes after I say `y` to pulling the image from the repository i.e.:

```
Container does not exist. Creating      image=quay.io/eris/eris-cm:0.11.4
The Docker image not found locally      image=quay.io/eris/eris-cm:0.11.4
Would you like the marmots to pull it from the repository? (y/n):
```

Then nothing happens, i tried verbose/debug output but nothing happens after the `y`

This has worked before, but the version `0.11.4` is also a very old version, and one with security issues.
I've tried this on `GCS` with `debian`, and on an `AWS linux` instance, and on a local `kubuntu` install.
The GCS would eventually download the image after trying the command again and again and then pressing enter a few times (I've noticed this with `npm` a lot, that something hangs, but enter or space breaks it out). When I `enter` more than 2 times it states: 
`Cannot start a container based on an image you will not let me pull`
And sometimes: `User refused to pull` before above message

Same problem with the third line in the getting-started example: `eris chains new test_chain --dir ~/.eris/chains/test_chain`

However, this **does** work: `eris services start eth`

Docker: 1.11.2
Eris 0.11.4
OS: linux (debian, kubuntu & amazon) & windows 10 (docker interactive shell)

So whether this is an issue with `quay.io` I'm not sure, but since other version do seem to work it shouldn't be their fault.

(Edit: `eris services start eth` does not actually start anything, so it seems it does need the 0.11.4 it tried to fetch but doesn't)

**Comment by pietv** [comment]
@BlockChanger thank you for reporting the issue. Yes, the "freeze" is a known issue and has been fixed in the 0.12.0 version: https://github.com/eris-ltd/eris-cli/issues/703

And no, this has nothing to do with Linux distribution, but rather the Unix terminal handling.

The easy fix is to always run `eris init` before starting or making a chain (the `eris-cm` image is among those which are pulled with `eris init`), the other fix is to upgrade to a 0.12.0 binary from here: https://github.com/eris-ltd/eris-cli/releases

> However, this does work: eris services start eth
That's expected, but reasons are again, terminal handling (starting `eth` doesn't require putting the terminal into raw mode, if you're curious).

Again, thank you for bringing this up!
