### ISSUE TITLE
Error moving keys: Docker: Cannot link to a non running container

### ISSUE THREAD

**Issue by BlockChange** [eris-ltd/eris-cli#776]
When I run: `eris chains new simplechain --dir $chain_dir_this` from https://docs.erisindustries.com/tutorials/chain-making/

`Error moving keys: Docker: Cannot link to a non running container: /simplechain-eb510b85-509c-4c49-9941-7d16fb5483f8 AS /interactive-6a325b25-808f-48f4-882a-841c0ceb9d17/chain`

I've set the `$chain_dir_this` correctly. And the `eris chains make --account-types=Root:2,Full:1 simplechain` command ran without errors..

I only have this problem on cloud instances, not on my local (k)ubuntu machine. One instance on GCS with debian and the other on Amazon Linux. 

I'm suspecting this might be a Unix terminal handling issue then?

Running `eris init` does not help

- `docker version` - 1.11.1
- `eris version` - 0.11.4

**Comment by zramsay** [comment]
Hi @BlockChange thanks for the report. Interesting that it is happening only on some OSs. IIRC this has been fixed since `eris version 0.11.4` Could you try updating to 0.12.0 and let us know if the problem persists? There is something weird going on with linking/volumes-from (see e.g, #780) although this should be a seperate issue entirely.

**Comment by BlockChange** [comment]
I eventually fixed this by removing the chain and create it again. Still not clear why it happened though.
