### ISSUE TITLE
`eris chains logs x` outputs wrong character encoding

### ISSUE THREAD

**Issue by BlockChange** [eris-ltd/eris-cli#777]
After running `eris chains logs simplechain` from https://docs.erisindustries.com/tutorials/contracts-deploying/

I get some weird output:
![image](https://cloud.githubusercontent.com/assets/20183083/16447888/fea53954-3dee-11e6-982e-eb87b266b904.png)

Important to note that **I'm running this in a Google Cloud SSH in a browser window**, so it is at least partially an issue with google. Likely something to do with character-encoding. 

What I find strangest about it, is that after it my commandline is scrambled as well:
![image](https://cloud.githubusercontent.com/assets/20183083/16448041/b36bdc76-3def-11e6-944c-816672686d3b.png)

Since I've not had this with anything else in the GCS-webterminal, this might be fixable on Eris' side.

docker version - 1.11.1
eris version - 0.11.4

**Comment by BlockChanger** [comment]
Here an example to see exactly where it starts to misbehave, after running `eris services logs idi`:
![image](https://cloud.githubusercontent.com/assets/20183083/16453892/c932b95c-3e0e-11e6-974e-3d9a27f1daf8.png)

Right when it's supposed to output `> node app.js`

**Comment by zramsay** [comment]
I suspect there's hidden characters with the logs getting piped out of the docker container. I encountered a similar issue once before but not as severe. Also weird that the behaviour persists. Can you `reset` the terminal & it goes away?

**Comment by pietv** [comment]
I was able to reproduce this on **Google Cloud SSH** in the browser. As the @zramsay suggests this has to do with the terminal escape sequences rather than an encoding. The logger library is using the hardcoded escape sequences which don't use terminal database which messes the console window. 

Currently the logger used by the erisdb software is being replaced to a new terminfo(5) aware which will fix the issue. cc @benjaminbollen @silasdavis.

To fix the issue temporarily, you can pipe the log output into a `cat -v` command to disable interpretation of special symbols `eris chains logs x|cat -v` and the `reset` command should indeed fix the issue for you on the host.

**Comment by zramsay** [comment]
somewhat related to #612

**Comment by compleatang** [comment]
am closing this for now. once we move to 0.12.0-rc2 this fix should be testable.
