### ISSUE TITLE
Setup a chain in a same network

### ISSUE THREAD

**Issue by yogaa** [eris-ltd/eris-cli#821]
Hi All,

 I want to setup a chain on my machine i.e using virtual machine & docker and make it available to other nodes (peers) within the same network without using cloud.

 Or may be create two vm's on the same machine and share a common chain between the two

Any Links and references on the same would be a great help.

Thnks,
Yogaa

**Comment by zramsay** [comment]
Hi @yogaa there are two ways to do this: 1) create several docker-machines;
 [this tutorial on docker-machine](https://docs.erisindustries.com/tutorials//tool-specific/docker_machine/) should get you started ... all your `docker-machine`s can be created with `--driver virtualbox` so that they run locally rather than the cloud. Each docker-machine will have an IP that you'd put in the `seeds = "IP:46656"` in the `config.toml` and each you'd start each node with `eris chains  new someChain --dir someDir --machine firstMachine` and so on

2) starting > one node on a single machine is possible, you'll just have to `eris chains new ... --publish` which will randomized the ports in order to avoid conflicts. note that you'll need to check the mapped ports with, eg. `eris chains ls -a` and use the random port that is mapped to 46656 as the port in the `seeds = IP:34267` or whatever the random port is.

Hope this help!

**Comment by zramsay** [comment]
also feel free to shoot me an e-mail: zach@erisindustries.com for a slack invite.

**Comment by yogaa** [comment]
Hi,

 Is it mandatory to deploy our chain on the cloud to make it available on multiple machines.

Regards,
Yogaa

**Comment by compleatang** [comment]
Not mandatory at all, you'll need machines with fixed IPs though to be most efficient in first peer problem.

**Comment by yogaa** [comment]
I am unable to setup the same could you please help me with some links / url which would help me easily set up the same.

i did go through the eris documentation _https://docs.erisindustries.com/tutorials/advanced/chain-deploying/_ 

it would be great if any other link which would help me setup the same

thanks again Casey !

**Comment by compleatang** [comment]
? setting up the chain is the same paradigm covered in that tutorial so I'm unclear what you're asking exactly... While that tutorial does cover cloud deployment if you're just using a LAN or something else the process is more or less the same.

**Comment by R1j1t** [comment]
@zramsay Thank you very much for your answer. I used the option with `--ports` flag. But now when I looked at [chain deployment on monax website](https://monax.io/docs/documentation/cm/latest/examples/chain-deploying/), the problem came out to be 1) there is no config.toml file in the default folder (I did run `eris init`)
2) now connecting the ports is also something which I didn't find anywhere.
I would be grateful if you could help here.
