### ISSUE TITLE
feature request: write errors (e.g. from `eris pkgs do`) to STDERR and return error code

### ISSUE THREAD

**Issue by SCBuergel** [eris-ltd/eris-cli#836]
Currently `eris pkgs do` outputs errors such as compile errors to STDOUT and exits always with exit code 0, disregarding if there was an error or not. For automating build tools it would be great to instead write errors to STDERR and change the exit code. This might apply to other error messages as well. This would then allow build tools to detect that something went wrong instead of having to parse the entire STDOUT stream for specific errors.

Since the RC binaries are not working I am working on Eris 0.11.4 installed from binary on Ubuntu 16.04 x64.

**Comment by zramsay** [comment]
++ great idea. I'll leave it to @pietv to confirm the feasibility of this given how we use docker

**Comment by pietv** [comment]
@SCBuergel thank you for the suggestion! 

1. `eris` CLI uses the exit code 1 to notify shell if an error occurred and exit code 0 if the operation was successful. The fact that you run the `eris pkgs do` command and it reported and error textually with an exit code 0 means that it wasn't handled as such (package management container returned exit code 0). It would be nice if you could remember which error message that was to turn the `eris pkgs do` to a proper error.

2. STDOUT is currently used for logging and error codes so that it is simpler to redirect output (`eris|less` vs `eris 2>&1 |less`), but filtering the error stream from output stream makes more sense.

A few other notions:
* Container errors rendered on STDERR on a guest operating system will still appear on STDOUT on the host machine (`O` means STDOUT in the below example) and it is sometimes preferable to output container messages in real time instead of collecting them in a buffer (meaning these will be on STDOUT if they're errors).

```
# annotate-output docker run -ti ubuntu echo test '>/dev/stderr'
10:01:02 I: Started docker run -ti ubuntu echo test >/dev/stderr
10:01:02 O: test >/dev/stderr
10:01:02 I: Finished with exitcode 0
```

* Errors as well as any other messages are reported through the logging facility which uses one output stream for everything exclusively, so either STDOUT or STDERR for every message (including informational or debug ones). 

* Will prefer to keep the help screen to be reported on STDOUT instead of STDERR (unlike most CLI software).

**Comment by pietv** [comment]
Feature is implemented. Closing.
