### ISSUE TITLE
How to create multiple nodes on a single machine

### ISSUE THREAD

**Issue by infinius12345** [eris-ltd/eris-cli#862]
Please include in your bug report:

**docker version**
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64
- [Eris CLI Version: 0.12.0-rc3 ] **`eris version`**

**- [ Ubuntu 14.04 on Virtual Box]** 

Hi,

I am currently trying to create multiple nodes on the same machine and i cant nest VM's so using Docker Machine is not possible is there another way to do this? I read somewhere that you can create multiple nodes by just running eris chains new .. --publish to randomize ip and add it to config.toml but every time i execute eris chains new.. --publish and run eris chains ls -a i get the following result.
0.0.0.0:1337->1337/tcp, 0.0.0.0:46656->46656/tcp, 0.0.0.0:46657->46657/tcp
with no ports randomized..

**Comment by zramsay** [comment]
Hi @infinius12345, thanks for the bug report. I can confirm that there is unexpected behaviour with the `--publish` flag. I was able to reproduce your issue only when running `eris chains new --dir ~/.eris/chains/someChain --publish` for the second time, on a chain that had been previously new-ed and subsequently stopped. Note: the `eris chains new` command should only ever be run once per node (this command will be deprecated (see #651) and the pipeline to starting a chain smoothed out).

Can you try creating a fresh chain from scratch?
```
eris chains make --chain-type=simplechain newChain
eris chains new --dir ~/.eris/chains/newChain newChain --publish
```
The above should work reliably *on brand new chains*. However,
```
eris chains make --chain-type=simplechain otherChain
eris chains new --dir ~/.eris/chains/otherChain otherChain
eris chains stop otherChain
eris chains start otherChain --publish
```
does not work as advertised (ports are *not* randomized after `eris chains start`, as the flag would imply). Thank you for identifying this bug. Concurrently, the below won't work either.
```
eris chains make --chain-type=simplechain shinyChain
eris chains new --dir ~/.eris/chains/shinyChain shinyChain
eris chains stop shinyChain
eris chains new --dir ~/.eris/chain/shinyChain shinyChain --publish
```
However, replacing `eris chains stop shinyChain` with `eris chains rm shinyChain -xf` will allow you to re-run `eris chains new` with `--publish`.

**Note:** There is also the `--ports` flag that accepts a csv string for specific ports you'd like to assign (rather than randomizing them). Example: `eris chains new --dir ~/.eris/chains/someChain someChain --ports 51337,56646,56647` will re-assign the ports. 

This command sequence is in flux, feel free to leave your input in #651 so that we can make it as seamless as possible.

**Comment by infinius12345** [comment]
i agree with the change to eris chain start, but my question still remains, is it possible to create multiple nodes on a single machine? i cant use docker-machines because of virtualbox nesting constrains.. as i was reading your comment on https://github.com/eris-ltd/eris-cli/issues/821to me it seemed like i had to use eris chains new multiple times to create multiple nodes.. apologies but could you please clarify?

**Comment by zramsay** [comment]
this issue https://github.com/eris-ltd/eris-cli/issues/858 should clarify the problem, with the block of code illustrating the solution.

**Comment by infinius12345** [comment]
Hi,
When i use eris chains new advchain1 --dir advchain/advchain_validator_000 --env CHAIN_ID=advchain
it does not create a new dir under chains i only have a toml file
~/.eris/chains$ ll
total 32
drwxrwxr-x 6 infinius infinius 4096 Aug 11 09:24 ./
drwxrwxr-x 11 infinius infinius 4096 Aug 5 09:36 ../
drwxrwxr-x 2 infinius infinius 4096 Aug 11 07:38 account-types/
drwxr-xr-x 31 infinius infinius 4096 Aug 11 09:22 advchain/
-rw-rw-r-- 1 infinius infinius 201 Aug 11 09:24 advchain1.toml
drwxrwxr-x 2 infinius infinius 4096 Aug 11 09:20 chain-types/
drwxrwxr-x 2 infinius infinius 4096 Aug 11 07:58 default/
-rw-rw-r-- 1 infinius infinius 460 Aug 4 21:34 default.toml

so when i use
~/.eris/chains$ eris data exec advchain1 -- mv /home/infinius/.eris/chains/advchain1 /home/infinius/.eris/chains/advchain
mv: cannot stat '/home/infinius/.eris/chains/advchain1': No such file or directory
Container interactive-2129aecf-e28d-4b90-85b2-35766a1be069 exited with status 1

Please advise/help!

**Comment by compleatang** [comment]
for the exec command, you will want the `eris` user cause that is running inside the containers where we exclusively use the `eris` user. so the data exec should be:

```
eris data exec advchain1 -- mv /home/eris/.eris/chains/advchain1 /home/eris/.eris/chains/advchain
```

**Comment by infinius12345** [comment]
ohh i understand! I had assumed something wrong there thank you for clearing the concept it works now

**Comment by zramsay** [comment]
:+1: can we close the issue?

**Comment by infinius12345** [comment]
Sure! Thank Your for your help! you guys are great :P will come back if i have another issue

**Comment by R1j1t** [comment]
I created nodes based on your suggestion of using `--publish` flag. But now If I have to connect those nodes then how should I do it. 
Background: I created a chain with 3 participant account and 2 validator account. created nodes 2 nodes, one for each validator and participant. Now how should I connect them? 
I read their config.toml file and both have same `node_laddr` and same `port`. Apologies if you find this silly.
@infinius12345  @zramsay
