### ISSUE TITLE
`services restart`

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-cli#95]

**Comment by compleatang** [comment]
good idea. 

currently `update` does the restarting, but it is pretty heavy handed (it will stop the container if its running, remove the container, pull a new image, rebuild the container, and restart the container if it was running previous to the update). 

`update` may not be the most user friendly though. what we should probably do is to add `restart` as an alias to `update`. 

see: https://github.com/spf13/cobra/blob/385fc87e4343efec233811d3d933509e8975d11a/command.go#L41

then we should reverse the default which is that update `pulls` in a new image. which upon reflection is probably overkill. we would only want to pull if a flag was sent rather than as the default. 

to switch the default from skipPull to pull.

change this flag to utilize the do.Pull bool: https://github.com/eris-ltd/eris-cli/blob/develop/commands/services.go#L270

change this line to reference the new bool populated by the new flag: https://github.com/eris-ltd/eris-cli/blob/develop/services/manage.go#L243

and finally change this line to be the opposite of what it currently is: https://github.com/eris-ltd/eris-cli/blob/develop/perform/docker_run.go#L286

**Comment by zramsay** [comment]
`services update` does what it used to do but only `pulls` if '--pull=true`
`services restart` == `services update` -> commands are functionally identical; that's the point of Aliases.
