### ISSUE TITLE
setting up eris on ARM

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#990]
https://twitter.com/jbrodier/status/786157224066293760

**Comment by zramsay** [comment]
related to #961, the install script should also work:
https://github.com/eris-ltd/hello-eris/blob/master/cloud/arm/setup/setup.sh

**Comment by zramsay** [comment]
closing as resolved (see twitter thread)

**Comment by jbrodier** [comment]
Hi,
I'm getting two problems when building Eris with setup.sh on RaspPi 3B :

Line 158, "git checkout armhf" gives :
 >   error: pathspec 'armhf' did not match any file(s) known to git.

Line 159, "go build" gives :
 >   ../pkgs_arm.go:88: undefined: pkgs.ImportPackage
 >   ../pkgs_arm.go:94: undefined: pkgs.ExportPackage

I've no such methods 'ImportPackage'/'ExportPackage' in github.com/eris-ltd/eris-cli/pkgs/pkgs.go
Have these commands been removed ? 

Thanks.

jbrodier, from twitter

**Comment by zramsay** [comment]
Indeed they have. That branch is also gone. For the time being, try `git checkout release_0.11`

**Comment by jbrodier** [comment]
Thanks, got eris-cli 0.11 compiled.

Now I'm unable to start the 'keys' service :

  > pi@raspberrypi:~/go/work $ eris services start keys
  > Error starting service keys: Docker: Cannot start container 0f54e6273643617da241d50ef80a040c51191cfda6a0ad4ff4dd789ce0df4856: [9] System error: exec format error

Did 'eris init' pulled the wrong images ? (latest ?)

  > pi@raspberrypi:~ $ eris init --yes
  > Eris root directory doesn't exist. The marmots will initialize it for you
  > Pulling default Docker images from quay.io
  > Pulling image 1 out of 7                image=quay.io/eris/base
  > Pulling image 2 out of 7                image=quay.io/eris/data
  > Pulling image 3 out of 7                image=quay.io/eris/keys
  > Pulling image 4 out of 7                image=quay.io/eris/ipfs
  > Pulling image 5 out of 7                image=quay.io/eris/erisdb
  > Pulling image 6 out of 7                image=quay.io/eris/epm
  > Pulling image 7 out of 7                image=quay.io/eris/eris-cm
  > Successfully pulled default images
  > Initializing default service, action, and chain files
  > Initialized Eris root directory          root=/home/pi/.eris


Should I reference another image to pull in $HOME/.eris/services/keys.toml ?
  > image = "quay.io/eris/keys:arm-0.12.0"

Which image for a RaspPi 3B, working with eris-cli 'release_0.11' (advised above) ?

Thanks !

jbrodier.

**Comment by zramsay** [comment]
what's the output of `docker images` ? That looks like the correct keys image to pull, though our ARM docker images may be a tad out of date.

**Comment by jbrodier** [comment]
I reinstalled Raspbian and Eris R0.11 from scratch but got the same error :

> export GOROOT=/usr/local/go1.6
> export GOPATH=/home/pi/go
> export GOVERSION="1.6"
> export PATH=$PATH:$GOPATH/bin
> export PATH=$PATH:$GOROOT/bin
> export NODEVERSION="4"
> export DOCKER_HYPRIOT_VERSION="1.10.3-1"
> export DEBIAN_FRONTEND=noninteractive
> curl -sSL https://deb.nodesource.com/setup_"$NODEVERSION".x | sudo -E bash
> sudo apt-get install -y bc jq gcc git build-essential nodejs
> curl -sSL https://www.dropbox.com/s/1v8uxdn6oo48t2g/go1.6.tar.gz?dl=0 | sudo tar -C /usr/local -xzf -
> wget https://downloads.hypriot.com/docker-hypriot_"$DOCKER_HYPRIOT_VERSION"_armhf.deb
> sudo dpkg -i docker-hypriot_"$DOCKER_HYPRIOT_VERSION"_armhf.deb
> sudo usermod -a -G docker pi
> curl -sSL -o ./simplechain.sh https://raw.githubusercontent.com/eris-ltd/hello-eris/master/cloud/x86/chains/simplechain.sh
> chmod a+x simplechain.sh 
> chown pi:pi simplechain.sh 
> go get -d github.com/eris-ltd/eris-cli/cmd/eris
> cd $GOPATH/src/github.com/eris-ltd/eris-cli/cmd/eris
> git checkout release_0.11
> go build
> go install
> export ERIS_PULL_APPROVE="true"
> export ERIS_MIGRATE_APPROVE="true"
> eris init --yes
> eris services start keys

Error starting service keys: Docker: Cannot start container 8564b7eb33e6e1424363e649cb19ef7164cf4f2c2087682827e119bec3a9926e: [9] System error: exec format error


> docker images
REPOSITORY             TAG                 IMAGE ID            CREATED             SIZE
quay.io/eris/keys      latest              03236a089790        46 hours ago        244.2 MB
quay.io/eris/erisdb    0.11.4              3ddfddfa8afe        7 days ago          617.8 MB
quay.io/eris/eris-cm   0.11.4              6e9d8841eda3        4 weeks ago         388.3 MB
quay.io/eris/data      latest              139360deb878        7 weeks ago         205.3 MB
quay.io/eris/ipfs      latest              a660d3b2494f        4 months ago        353.9 MB
quay.io/eris/base      latest              cd782894a068        4 months ago        738.9 MB
quay.io/eris/epm       0.11.4              7505721901fa        5 months ago        764.3 MB


The 'keys' image tag is 'latest' because eris-ltd/eris-cli/version/images.go doesn't append a VERSION to the image name. 

> var (
>         ERIS_REG_DEF = "quay.io"
>         ERIS_REG_BAK = "" //dockerhub
>         ERIS_IMG_BASE = "eris/base"
>         ERIS_IMG_DATA = "eris/data"
>         ERIS_IMG_KEYS = "eris/keys"
>         ERIS_IMG_DB   = fmt.Sprintf("eris/erisdb:%s", VERSION)
>         ERIS_IMG_PM   = fmt.Sprintf("eris/epm:%s", VERSION)
>         ERIS_IMG_CM   = fmt.Sprintf("eris/eris-cm:%s", VERSION)
>         ERIS_IMG_IPFS = "eris/ipfs"
> )


Should i pull 'quay.io/eris/keys:0.11.4' instead of 'latest' ?
See here :  https://quay.io/repository/eris/keys?tag=latest&tab=tags

Thanks !

jbrodier.

**Comment by zramsay** [comment]
ah, right. I forgot - the ARM compatibility was not in the 0.11 series. You'll want to checkout this release https://github.com/eris-ltd/eris-cli/releases/tag/v0.12.0-rc1, where `version/files_arm.go` was added. That'll pull the arm compatible images

**Comment by jbrodier** [comment]
It worked ! 

pi@raspberrypi:~/go/src/github.com/eris-ltd/eris-cli/cmd/eris $ eris services start keys
pi@raspberrypi:~/go/src/github.com/eris-ltd/eris-cli/cmd/eris $ eris services ls 
SERVICE     ON     CONTAINER ID     DATA CONTAINER
keys        *      6813ed9b93       66c4f68145

Thanks !

jbrodier.

**Comment by zramsay** [comment]
awesome! closing as resolved.
